---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8up-executor
  labels:
    app.kubernetes.io/name: k8up
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups:
      - k8up.io
    resources:
      - snapshots
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch